### ISSUE TITLE
Deeper solution comparisons

### ISSUE THREAD

**Issue by slorber** [gothinkster/realworld#113]
Hi,

First thanks for this great project. I've also been working on something quite similar some years ago [here](https://github.com/slorber/scalable-frontend-with-elm-or-redux)

I think it would be very interesting to have more comparison data across project. I'm thinking about stuff like bundle size etc... For example [https://hnpwa.com/](https://hnpwa.com/) is providing lighthouse stats which is useful to compare frontend solutions.

**Comment by Cameron-C-Chapman** [comment]
There was a discussion about this with issue #108. I think the consensus is that those stats could be valuable but there are so many variables that realworld wouldn't want to promote those statistics as some sort of conclusion on the framework being used. Maybe one front end implementation is bigger in size but the maintainer could argue their solution is more testable than another solution, one implementation has more lines of code and files but the maintainer argues it's more flexible, etc.

@EricSimons mentioned in #108 that if someone were to do writeup on the realworld implementations that had some performance or other comparisons he would feature it in the README but it probably doesn't need to be a part of the core project/spec.

**Comment by brwr** [comment]
Agreed with @Cameron-C-Chapman.

As mentioned, the problem with benchmarks is that they are incredibly misleading. Just because one tool can render a list of 10,000 items more quickly than another does not imply that it is better in general. At best, it means that it's better at rendering a list of 10,000 items.

I'm going to close this as I think the consensus is that this isn't something we want to pursue as a project for the time being. Anyone who disagrees should feel free to comment.
