### ISSUE TITLE
[Bug]: (a11y) Text contrast it beyond bad on the primary example

### ISSUE THREAD

**Issue by J-Sek** [gothinkster/realworld#1598]
### Relevant scope

Frontend specs

### Description

[demo.realworld.how](https://demo.realworld.how/) acts as the primary example of the "realworld" web app, but it immediately screams "_bad UX, bad contrast, unreadable, outdated_". I wish I could create a PR with text color tweaks, but upon hours of search, I could only find an abandoned (but still linked from the main Readme) repo for a Bootstrap theme.

**Comment by jitendrajaria** [comment]
let's make this a improvement, not a bug?

**Comment by J-Sek** [comment]
> _let's make this a improvement, not a bug?_

Sure, don't mind :)

Possible resolutions:
- unarchive bootstrap theme repo
- or put the CSS files somewhere in the main repo so people can suggest improvements (they would need to land on [demo.realworld.how](https://demo.realworld.how/) eventually
- or point me in the right direction. Maybe everything is set up but I have missed a readme page or some important link

**Comment by geromegrignon** [comment]
Hi @J-Sek, I'll investigate this week about the more appropriate way to make it sustainable (the current doc info links to a domain the current team does not have access upon). It'll more likely about exposing an URL on api.realworld.how and add the styles file on this repo.

Mind changes will be limited to color changes. Due to the project's nature, we can't update implementations, and the goal is still to provide a way for the community to compare frameworks/libraries.
