### ISSUE TITLE
This project is very inactive

### ISSUE THREAD

**Issue by quanla** [gothinkster/realworld#173]
It takes weeks to get a response from this project's developers. The idea behind this is very nice, but with this inactivity, things are falling apart

**Comment by Cameron-C-Chapman** [comment]
Hi @quanla, sorry you feel that way. Keeping up with open source can be tough sometimes, everyone has multiple things going on and we try our best but I know personally I've been less active over the last month or so due to some schedule issues.

I disagree that the project is "falling apart", since the goal is to provide people an easy way to experiment and showcase different frameworks easily and I believe we still do that. There are a couple of projects that we need to get finalized and added but for the most part I don't think there are a lot of outstanding issues necessarily waiting on the admins.

Is there a particular issue that you're having a delay on that you'd like to see get pushed through?

**Comment by quanla** [comment]
Hi Cameron, thank you for responding. It is great to hear from someone... at last. And yes, I have #161 open issue for a finished implementation of full spec Realworld demo using React, in it's pure form. Would be great if you can have a look and leave a comment. Thanks again

**Comment by Cameron-C-Chapman** [comment]
We're working on getting caught up but since there are GitHub's built in pulse metrics and any inactivity is pretty specific to individual project submissions (working on getting yours added) I'm going to go ahead and close this.

If you have any specific suggestions to help the project you can open an issue with those ideas and we can address those.
