### ISSUE TITLE
 "following": false

### ISSUE THREAD

**Issue by rajeget** [gothinkster/realworld#183]
Hi
This is not a issue , but want to understand the API , In this API Strucutre https://github.com/gothinkster/realworld/tree/master/api

In Profile API what does following : false means ?

{
  "profile": {
    "username": "jake",
    "bio": "I work at statefarm",
    "image": "https://static.productionready.io/images/smiley-cyrus.jpg",
    "following": false
  }
}

**Comment by Cameron-C-Chapman** [comment]
> following:false

 means that the authenticated user is not following the profile you are viewing. That following references whether or not _you_ are following that profile.

**Comment by rajeget** [comment]
Hi
Thanks @Cameron-C-Chapman  .Just to make sure I understood, the authenticated user who is requesting GET profile , is he access this user ( in thi case jake) .
What about if the user access his own GET profile API ?

**Comment by Cameron-C-Chapman** [comment]
If you view your own profile you will see `following: false` since you can't follow yourself. If you view a different users profile you will see if you are or are not following that user.

I'm going to go ahead and close this. If you have more questions or notice any problems with the API feel free to open other issues or I can open this one back up if it's related.
