### ISSUE TITLE
Angular application error in local ( Content-Type:text/plain) with spring boot

### ISSUE THREAD

**Issue by ajitbapina** [gothinkster/realworld#185]
I have tried to run as backend (https://github.com/gothinkster/spring-boot-realworld-example-app) and frontend (https://github.com/gothinkster/angular-realworld-example-app) .

I am trying to register through angular app but not able to call api backend.
I debug it and found below error.

Request URL:http://localhost:8080/users
Request Method:POST
Status Code:415 
Remote Address:[::1]:8080
Referrer Policy:no-referrer-when-downgrade

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Connection:keep-alive
Content-Length:64
Content-Type:text/plain
Host:localhost:8080
Origin:http://localhost:4200
Referer:http://localhost:4200/register
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
It seems to be calling api   Content-Type:text/plain.

I have tested my api via postman,it is working fine.

**Comment by Cameron-C-Chapman** [comment]
Hi @ajitbapina. Any issue you find in an implementation should probably be a bug in that repository. So if you are seeing this issue with the spring-boot backend repo I would file an issue there so the owner can address it.

I'm going to close this now since it doesn't really apply to this repo but if you have any more questions or you disagree with that let me know and I can take another look.

**Comment by ajitbapina** [comment]
thanks. now it is fixed
