### ISSUE TITLE
Image Upload (API Spec)

### ISSUE THREAD

**Issue by xsoh** [gothinkster/realworld#26]
Hello, 
Thanks for this great specs.
I have suggestion for adding a image upload feature in the API spec while it is tricky thing and mostly needed.

Thanks

**Comment by EricSimons** [comment]
Great suggestion! As you probably know, the current way you update your profile picture is by providing a URL to an image. This was actually done intentionally to allow image upload support in the future. Specifically, here's how it would work:

1.  Have the frontend upload the image to a storage service like Amazon S3
2. S3/etc sends back the URL to the frontend for the uploaded image upon upload success
3. Update the user's info with that image URL via the backend API

I think framework agnostic examples of this would be good to have in this repo (i.e. vanilla examples of uploading to AWS, Azure, Digital Ocean, and other storage service providers). Thoughts?

**Comment by eko24ive** [comment]
@EricSimons is it required to use external file storage e.g. AWS ? Is there are some caveats/restricions  when using your own server ?

**Comment by EricSimons** [comment]
@eko24ive nope, you could technically have the upload go through the backend as well. However, it's generally not a good idea to do that because it can easily kill your server performance. Instead, if you have the client upload to a storage server that then webhooks to your server on success, you can process the pre-uploaded data in-datacenter in a non-blocking way that won't affect your API server.

**Comment by Cameron-C-Chapman** [comment]
So @EricSimons are we thinking this falls under the extra credit umbrella or is this something we want to consider for the core spec? It doesn't feel like something that fits with the core spec since it would require adding storage provider credentials to support it.

**Comment by SandeeshS** [comment]
I think we can keep this for the next version of the spec. This isn't a simple extra credit task since this requires changes in both frontend and backend to support this. Which would need changes from 2 different parties to make this work. I don't feel that we can accommodate this with the current spec.

**Comment by geromegrignon** [comment]
Closing it as it's out of the core spec.
