### ISSUE TITLE
Rust / Rocket / Diesel / Mysql - Backend Application

### ISSUE THREAD

**Issue by navinkumarr** [gothinkster/realworld#272]
https://github.com/navinkumarr/rust-realworld-example-app

**Comment by anishkny** [comment]
Could you clarify how this is different from: https://github.com/gothinkster/rust-realworld-example-app

**Comment by navinkumarr** [comment]
Here are a few points because of which I started working on this application. Don't see these in the example application you have posted above.

1. It is built according to the Rocket framework standard (Trying to make a complete application with proper error handling, database connection pooling, support for master/slave architecture for database etc).
2. I have seen many example applications using Postgres. This one has the implementation for Mysql (Even though using an ORM, a straightforward example still helps).
3. Clean architecture (Could use this app architecture for writing bigger applications since it is properly layered).

Do let me know what you think @anishkny

**Comment by anishkny** [comment]
I am not an expert on Rust. It might be worth discussing with their [contributors](https://github.com/gothinkster/rust-realworld-example-app/graphs/contributors) if this is different enough? @davidpodhola, @leia, 

cc: @Cameron-C-Chapman

**Comment by davidpodhola** [comment]
I will support [the new implementation](https://github.com/navinkumarr/rust-realworld-example-app) by @navinkumarr.
Not only it is using a different database, but also using a different framework; [Rocket](https://rocket.rs/) is nice (note: we did not use it because we were told it is old and un-updated).
Also please note our implementation was done when we were very Microsoft oriented (everything in the repo is Windows-oriented); I hope the new one is multiplatform.
I think @navinkumarr you could at least reuse the tests we did, we had a very good code coverage.

**Comment by navinkumarr** [comment]
@davidpodhola  Thank you for reviewing the project. Your feedback is much appreciated. Will surely take reference from your application wherever possible.

**Comment by anishkny** [comment]
Go for it @navinkumarr best luck! Would be good if you could document differences from the first repo.

**Comment by ezracelli** [comment]
@navinkumarr Is this still WIP? I'd love to take this on using the Rocket 5.0 beta

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
