### ISSUE TITLE
🗄🔧 Node + GraphQL

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#46]
# Current Status

- ### Codebase in progress:<br /> [thebergamo/realworld-graphql](https://github.com/thebergamo/realworld-graphql)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/graphql-relay-apollo](https://gitter.im/realworld-dev/graphql-relay-apollo)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by thebergamo** [comment]
@EricSimons first step done!
https://github.com/thebergamo/realworld-graphql

I think by the end of the week, I can update the repo with a simple boilerplate attending the basic specs for the APIs

**Comment by EricSimons** [comment]
Awesome! I just updated the issue status & created this logo for your repo's readme:

![graphql](https://cloud.githubusercontent.com/assets/556934/25366017/c00bde40-2921-11e7-9c91-be669ead5c44.png)

**Comment by thebergamo** [comment]
@EricSimons maybe will be greater if you use both graphql and apollo logos

**Comment by EricSimons** [comment]
Done :)

![apollo](https://cloud.githubusercontent.com/assets/556934/25449690/1d4553a0-2a82-11e7-83f4-6d7ef4ddeed0.png)

**Comment by thebergamo** [comment]
@EricSimons a first version is released! https://github.com/thebergamo/realworld-graphql

At this time, just have user and profile endpoint.

**Comment by EricSimons** [comment]
@thebergamo woah! This is awesome!! I'm gonna clone and play around with this over the weekend 😃 Does the Relay FE integrate with this yet? Seriously can't wait to test drive fullstack graphql!

**Comment by thebergamo** [comment]
I'm not sure, need to talk with Steve about the integration!

I will try to finish the spec until Monday. Not promise, but will try!

**Comment by xyclos** [comment]
Is anyone still working on this? the fork hasn't been touched in 2 years. I'd like to help out with this.

**Comment by anishkny** [comment]
Go for it @xyclos! Feel free to build on https://github.com/thebergamo/realworld-graphql

**Comment by thebergamo** [comment]
Holy lord! 2y already :(

**Comment by xyclos** [comment]
hey, @thebergamo @anishkny I was having a look at the existing repo and I have some questions:

why is this wrapping the restful api? wouldn't a more complete example implement the db connection, orm and the business logic for querying the data like the node express example does?

also, it seems the integration with hapi may be unnecessary now since apollo-server no longer requires a separate http server. I think hapi maybe over complicating things a bit. (removing hapi and implementing the db stuff has me leaning toward starting a new repo from scratch)

has any work been done for automatically testing that this correctly implements the spec? should the postman script be extended? should a new one be created specifically for gql implementations?

finally, can one of you help me to understand what is remaining todo with the existing repo?

thanks :)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
