### ISSUE TITLE
Add backend: Rust (Tide + Diesel)

### ISSUE THREAD

**Issue by LukeMathWalker** [gothinkster/realworld#467]
A backend implementation in Rust using [Tide](https://github.com/http-rs/tide) as web framework and [Diesel](http://diesel.rs/) as ORM.
The project passes all tests in the Postman collection and comes with its own set of unit and integration tests, checked in CI.

Not really sure on the process: do you want to check the project first or should I open a PR to add it to README? 😄 

_Repo_: https://github.com/colinbankier/realworld-tide

**Comment by azzamsa** [comment]
Any update about this?

Or should we just make it as PR?

**Comment by LukeMathWalker** [comment]
That comment is outdated - the spec is fully implemented.

**Comment by azzamsa** [comment]
I saw your reply 3 hours ago. But can reply now.

Turns out all opened TODO issue (https://github.com/colinbankier/realworld-tide/issues/1, https://github.com/colinbankier/realworld-tide/issues/5, https://github.com/colinbankier/realworld-tide/issues/6, https://github.com/colinbankier/realworld-tide/issues/7) already implemented.

It's indeed a happy news for us. Let's convert this issue into a PR.

**Comment by LukeMathWalker** [comment]
Shall I open one?

**Comment by azzamsa** [comment]
I think YES. but we need to be patient. Since there many really old PR not being merged yet.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
