### ISSUE TITLE
Push notifications (mobile)

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#53]
I was just thinking, it might be nice for us to host an APNS/GCM server that mobile apps can connect to and receive push notifications for (i.e. For notifications about comments, likes, etc on the users' conduit posts).

Push notifications are part of nearly every mobile app, so I think this would be a good addition to make it "real world". Thoughts?

**Comment by EricSimons** [comment]
Also, now that parse is dead, what is the most common way to host a push noti server?

**Comment by harshabonthu** [comment]
We use this to test / debug push notifications and it includes sample setup using PHP -> http://apns-gcm.bryantan.info 

I'm not familiar with the node packages but should be able to do the same using package for node.

Another alternative is we can configure Firebase notifications or Ionic.io and there API can be used to send push notifications.

`would this even be possible due to push noti certs? i.e. can we create a public cert that everyone could use?` - I think if we do the code signing using Fastlane tools, https://github.com/fastlane/fastlane/tree/master/pem and have a readonly apple account, anyone can sign the app, test push notifications using the readonly apple account to download the needed certs.

Code signing certs will be hosted on github repo and the readonly apple account will be used to download the certs while generating a build,etc. I've done this setup for private repos i.e CI setup for mobile apps but need to lookup on public repo setup (not sure on security)

**Comment by sohamnavadiya** [comment]
@EricSimons I would like to suggest to implement FCM notification for mobile apps.

**Comment by claytonschneider** [comment]
@EricSimons 

At [Blend](https://blend.com/) we use Amazon SNS for push notifications which works really well, but the infra setup required there might be a bit overkill for Realworld. I think [OneSignal](https://onesignal.com/) could be a good choice, it's free and there are SDK's available for [Ionic/Cordova](https://github.com/OneSignal/OneSignal-Cordova-SDK) and [React Native](https://github.com/geektimecoil/react-native-onesignal).
