### ISSUE TITLE
 No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by xixizhangfe** [gothinkster/realworld#549]
![image](https://user-images.githubusercontent.com/26836640/91373532-3359c800-e849-11ea-9ea3-e2531e03d63b.png)

**Comment by EJIqpEP** [comment]
Same for me. Any updates here?

**Comment by xAKLx** [comment]
Same

**Comment by Aisen60** [comment]
Same.I guess maybe the service had down

**Comment by xixizhangfe** [comment]
@anishkny hi, could you please help us out with the problem?

**Comment by chichinumber222** [comment]
Same. In most requests these errors

**Comment by dj0nny** [comment]
Same. Any updates?

**Comment by anishkny** [comment]
Can reproduce issue. Navigating to https://conduit.productionready.io/api/tags in browser causes `Error 502 Bad gateway`. Sometimes works from command line `curl` but not 100%. Looking...

**Comment by joeeames** [comment]
Working on the issue right now. if anyone is a CORS expert and wants to help ping me please.

**Comment by EJIqpEP** [comment]
I'm not an expert but can gladly help. From what I see there 2 problems:
1. 502 on requests randomly like server dies because of some backend error
2. CORS problems on requests. You need to have such header in every answer on server:
'Access-Control-Allow-Origin: *'
'Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS'
'Access-Control-Allow-Headers: Origin, Content-Type, Autorization'

**Comment by apai4** [comment]
Sorry for the delay here! I can confirm that one of the instances was returning errors inconsistently and wasn't being removed from the load balancer. The instance has been replaced and the servers are processing requests properly now. Apologies for the inconvenience, we'll be improving our infrastructure to prevent something like this from happening in the future.

**Comment by EJIqpEP** [comment]
Thanks for the fix. Looks good now.

**Comment by joeeames** [comment]
Thanks Albert
