### ISSUE TITLE
Standardize robust install/getting running instructions for each stack

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#62]
As pointed out by @anishkny [here](https://github.com/gothinkster/realworld/issues/56#issuecomment-297373727), getting folks up & running ASAP is key to the UX of RealWorld. 

Would love to ideate about how we can ensure that every repo has _amazing_ install/getting running instructions. I'd even be down to create screencasts for how to get every stack installed/running, if that would help 👍

**Comment by Cameron-C-Chapman** [comment]
So realworld would probably need to start with agreeing on a base image (Ubuntu, Red Hat, etc) and what the mechanism would be for individual repos to add their Docker tasks/scripts (assuming Docker here). Maybe a docker image that's part of the master branch is configured/updated with new scripts to pull in from other repos and those scripts could be executed individually as needed? I've only tinkered with Docker so I'm far from an expert but just wanted to throw a general idea out there.

If the standards were around how to create your Docker scripts and how to integrate them with the realworld project's Docker image then the need to standardize instructions is less important since the instructions are essentially in the scripts Docker is loading.

**Comment by deksden** [comment]
Some examinations: i can not start local node-express realworld server with react-redux client until i did not set port for client's web server: both app server and web client's server did use 3000.

**Comment by Cameron-C-Chapman** [comment]
Ya, I think port conflicts could be a common issue. That's why I like the idea of a standard port for front end and back end implementations with a consideration for different database port defaults. If something was specified like front end is always port 9090 and backend is always 9091 that could go a long way and the issue you ran into should go away, but there is still a bigger unified install issue that's an interesting challenge.

**Comment by EricSimons** [comment]
Yeah we actually attempted to lock specific ports for FE/BE for the currently supported stacks. The problem we ran into was that changing the port of various CLI's (specifically Angular & React) was either undocumented or required "ejecting" from the CLI boilerplate, which we didn't want to do. They may have changed this since then, but I haven't checked :/

Regardless, locking port numbers is definitely a good idea that we should implement ASAP. Maybe we could even have port ranges we could use? That way every stack could get assigned a unique port number, and thus you could run every single frontend/backend at the same time and have no port conflicts 😎

**Comment by Cameron-C-Chapman** [comment]
Here's what I see so far for the existing projects and common db's:

- Angular 2+: **4200** (default of the angular cli)
- React/Redux: **3000** (default of the create react app cli)
- AngularJS - **4000** & **4001** (browser sync and front end)
---
- Node/Express: **3000**
- Django: **8000** (and also expects a front end of **4000**)
- Rails: **3000**
---
- MongoDB: **27017**
- MySQL: **3306**
- Postresql: **5432**
---

Just looking at that there is already some conflict and I don't see a clean range. No matter what someone will need to update their project. Maybe front ends are 4000 - 4999 and backends are 8000 - 8999? We should avoid common db ports if possible in my opinion.

**Comment by EricSimons** [comment]
Thanks for taking the time to investigate & write this up! I def agree w/ avoiding all DB ports. We don't have to do ranges, — not even sure what the use case would be for running every frontend & backend at the same time (lol). Maybe for simultaneously comparing running stacks? Not sure if it's a solid enough value prop to warrant any potential headaches w/ port conflicts.

What do y'all think?!

**Comment by deksden** [comment]
React & Node definitely conflicts on default 3000 port. Looking at AngularJS 1/2/etc with 4000+ ports, i m sure it will be better to use something like 4100 port for React frontend.

Node and Rails on same 3000 port is not a problem at all, because running two backends at same time is strange idea. 

IMHO, only React project needs changing default port from 3000 to prevent conflicts with default backend's port for node/rails.
.
