### ISSUE TITLE
ReScript Demo & New user interface

### ISSUE THREAD

**Issue by vmarcosp** [gothinkster/realworld#643]
Hey!

I'm starting a new real-world app implementation using [ReScript](https://rescript-lang.org) and React... and I want to know if I can use a redesign version of this real-world app. It will have the same features and a very similar UI but with a new branding, logo, colors but the same name. Will be considered a valid implementation for the official list? I can send a preview of the UI before implementing :)

**Comment by geromegrignon** [comment]
Hello,

By providing specs, our goal is to make sure rules are available for everyone without having to argue on each submission.
As previous contributors respected these specs, it wouldn't fair to start accepting personal interpretations.

From the [specs](https://github.com/gothinkster/realworld/tree/master/spec) :
> We created a custom Bootstrap 4 style & templates to ensure all frontends had consistent UI functionality.

However if the goal is to provide a better or more modern user experience, we'll soon start working on a v2 of the current specs. Challenging the user interface is part of this new version and we'll welcome any contribution.
Meanwhile for the current version of the spec, we encourage people to follow them to add them to the implementation list.

**Comment by mvila** [comment]
I'd tend to think the same. In the current context, small variations of the UI should be accepted but not a complete redesign. However, for the v2 specs, my opinion is that we should be more flexible about UI design. Specs should address functionality, not presentation. It is something that should be discussed though.

@vmarcosp, in any case, I'd be curious to see a preview of your UI. 😄

**Comment by vmarcosp** [comment]
Thanks for answering!
I understand that all projects here are following the current spec. But if the project has the same features and a similar UI (navigation, sign-in page, list of items, etc) is not acceptable to be a real-world app that follows the technical requirements of the spec? I don't understand how a color or the logo of the UI can impact the comparison between two projects that delivers the same feature. I respect and understand your decision, I just want to help and contribute to this project :)

@mvila I'm working on the UI, but I have a preview of the wireframe and a draft of the branding/colors 😀

Wireframe of the sign-in page:
![Home.png](https://user-images.githubusercontent.com/20327229/115325905-d2c62500-a162-11eb-92e9-fc0b378be2c3.png)

**Comment by mvila** [comment]
@vmarcosp Your UI looks very nice, and it'd be a shame not to accept it.

@geromegrignon Could we make an exception?

**Comment by vmarcosp** [comment]
Thanks @mvila! 😄
If you like and agree we can work together on a new UI to the v2 or we can use this UI that I'm creating for my real-world app implementation :)

**Comment by mvila** [comment]
Since the v2 is not for tomorrow, I think you should start implementing a v1 with the UI you have in mind, and we'll see later if this UI can be used in the reference implementation of the v2.

**Comment by vmarcosp** [comment]
I totally agree @mvila, thanks for answering 😄

**Comment by geromegrignon** [comment]
As an exception which will showcase the future of the ui for next version we can integrate it.

However @vmarcosp, you must consider the ui is part of the specs, not an option.
The goal of these specs is to be able to provide rules for everyone, rather than having to argue with each implementation.
Such situation would lead to the end of the project as it doesn't scale. The former maintainer team tried to manually test and review each implementation and while they did a great work, having to spend time on individual contributions over the community did lead to having issues still opened after few years.

Your changes aren't just about colors : 
- having additional images means your implementation is less performant on a benchmark (as there are defined specs, consumers shouldn't be expected to dive into source code to see if there are any difference between 2 implementations)
- as you are using different stylesheets, consumers can't compare how you integrate the specs. If it sounds obvious for you, we had some use cases where integrating the stylesheet has a cost or need some changes. Such differences are valuables when you need to compare implementations.

Besides the submission of this implementation, we would be happy to work with you on the next version o the ui.

**Comment by vmarcosp** [comment]
@geromegrignon You're right, my changes aren't just about colors. Having additional images means that implementation is less performant, I agree. I would be happy if you accept my implementation with a new UI, maybe adding a disclaimer about an exception that you made for my case, I appreciate 🙏🏻 

> Besides the submission of this implementation, we would be happy to work with you on the next version o the UI.
Sure, I can help you with the design of a new spec / v2.

**Comment by geromegrignon** [comment]
About the exception, i would encourage you to add a disclaimer into the readme.md of your repository.

**Comment by vmarcosp** [comment]
@geromegrignon I can do this. So, for my case,  following the spec (features, sign-in page, feed page, etc) but with a new UI, might be accepted as an official implementation? Just to make it clear 😄

**Comment by geromegrignon** [comment]
Accepted! :+1:
