### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by Alonski** [gothinkster/realworld#65]
Internationalisation or i18n is critical for most production apps these days. 
I recommend adding an API for i18n. 
Have it return a JSON with all the tokens for all languages. 
Also an endpoint for only a specific language. 
Could setup a system to bring language contributers on board. 
Could implement a select in the UI to change language.

**Comment by brwr** [comment]
I agree that I18n is important, but it's also a huge amount of work. Specifically, purchasing translation files is too much to ask for an open source project.

I think this is outside the scope of the project though. The goal is to provide users with a high-quality codebase that introduces them to a language/framework. I18n doesn't help achieve that goal, so I think we should avoid it.

**Comment by Alonski** [comment]
No need to purchase translations. We can put everything in English only and setup a way for people to translate.

**Comment by brwr** [comment]
It's still outside the scope of the project. @EricSimons Thoughts?

**Comment by Alonski** [comment]
I am willing to implement this in Ember

**Comment by anishkny** [comment]
I think basically since the V1 api is "frozen" with multiple back and frontends already completed and many more actively in work, it would be too much work to enhance it to support i18n.

But out of curiosity, for discussion, what would this API look like? 

Could you expand on this:
> Have it return a JSON with all the tokens for all languages.
> Also an endpoint for only a specific language.

Does the backend expose extra endpoints? Or is this purely on front end. How exactly would the new API look in comparison to [v1 api](https://github.com/gothinkster/realworld/blob/master/api/README.md).


Also, about:

> I am willing to implement this in Ember

Since an important teaching point of this project is to sort of compare and contrast different stacks all trying to achieve the **same** thing, we would need a common API with clear implementation possible in most if not all stacks.

**Comment by Alonski** [comment]
About the endpoint:
While this could be a static translation of only English to start with. I think it would work better as an API. 
JSON would look like:
```
en: {
	hi: "Hi", 
	article: "article
	etc... 
} 
```
The Endpoint could be something like: apiUrl/i18n
Which brings all languages or with a parameter to only bring one language. 
Most libraries/frameworks that I looked at can consume this format of translations. 
Pretty much just a matter of consuming key value pairs. 

Even if we don't add a new endpoint to the spec. Having a static JSON file with just English wouldn't be bad as well.

**Comment by Cameron-C-Chapman** [comment]
We've agreed on what the minimum testing spec should be in the discussion in issue #90 so I think we can close this.
