### ISSUE TITLE
Link to false information in Readme

### ISSUE THREAD

**Issue by raulsebastianmihaila** [gothinkster/realworld#676]
Recently the README.md file was updated with a link to the 2020 article about the comparison between frontend implementations: https://medium.com/dailyjs/a-realworld-comparison-of-front-end-frameworks-2020-4e50655fe4c1 . That article contains false information regarding the size of the js bundle of the crizmas-mvc implementation. I wrote a comment there signaling this: https://raul-mihaila.medium.com/this-is-the-author-of-crizmas-mvc-ec5bc7817e5d , but the author of the original article didn't take notice. The difference is huge, the real bundle size (about 53KB) is less than 3 times lower than what the article says it is (178KB). (In the mean time I also did an update to the versions of the crizmas packages in the crizmas implementation but it has no significant effect on the bundles size.)

**Comment by mvila** [comment]
Maybe the author (@jacekschae) of the article didn't see your comment. Have you tried to contact him directly?

**Comment by jacekschae** [comment]
Hi, thanks for the information and I'm sorry if the information was not correct. The mistake was not intentional. Even though I check the information and try to make sure it's correct sometimes there are mistakes.

I checked my reference materials and at the time of writing this article the bundle size was 178

I believe this article from 2020 would need an update since there was a lot of information that changed. I promise to ask for your feedback before publishing an update to the article.

I'm sorry if the information in the article is not correct and I'm sorry for not taking the notice of the comment -- I'm not very good on reading them.

**Comment by raulsebastianmihaila** [comment]
@jacekschae do you plan to write a new article any time soon? I still think the best would be to edit the existing article since the information is very far from true and it doesn't do justice to crizmas-mvc. At least a note in the article would be welcome if it's too difficult to update the chart. Thanks!
