### ISSUE TITLE
[Feature Request] Solutions to keep the api empty of any nsfw content

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#708]
# 🚀 feature request

### Relevant scope
What is the scope of this request?

- [x] Frontend specs
- [x] Backend specs
- [ ] Other... Please describe:

### Description
The project provides a public API so everyone can consume it while testing or creating implementations.
Besides performance issues reported in #700, by being public, the API is vulnerable to attacks.

Lately, it resulted in having popular tags now populated with mature content (not aligned with our code of conduct).

As we are working on deploying a new database, we can't just rely on database resets to clear data.

### Describe the solution you'd like
While it would add complexity to the current specs, it would be easier to moderate content by adding a user management feature to :
- limit article creation
- moderate tags/articles
- block/delete accounts

Of course, it wouldn't be accessible for most people on the public website (admins only).

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mvila** [comment]
@geromegrignon I am not sure it is a good idea because it would increase the complexity of the app in a significant way. The goal of the RealWorld project is to build an app that is complex enough to cover the most important concepts of full-stack development, but it shouldn't be too complex.

I think the best option would be to:
1. Provide an easily runnable backend (e.g., a Docker image) that can be used by front-end developers locally.
2. Host an official backend that can be used by deployed frontend demos. This official backend could implement some additional features that are not part of the specs such as:
   - Request rate-limiting
   - Automatic removal of articles that are older than a week or two

**Comment by geromegrignon** [comment]
Resolved by the release of a new API with the limitations listed by @mvila
