### ISSUE TITLE
Postman Auth/Register Tests Don't Follow Spec

### ISSUE THREAD

**Issue by JackyChiu** [gothinkster/realworld#76]
I noticed in the Postman tests for `Auth - Register` it has a test which expects an `id` field in the response, but in the [spec sheet](https://github.com/gothinkster/realworld/tree/master/api) there's no expect `id` for the user field. 

Which is the correctly expected output?

**Comment by EricSimons** [comment]
I think this is a remnant of an older version of the spec we were adhering to. Feel free to disregard (and/or make a PR back here with the fixed version :) 

@apai4 looping you in here to double check (he created the original postman collection)

**Comment by SandeeshS** [comment]
Some more that I've noticed. I'm tired from working on the laravel backend. I'll try to consolidate and pull a PR when free.

## Spec

- Single article doesn't have tag list.

- Conflict in single article and feed route. If an article has the slug 'feed' then this would cause problems. Though the current api's used in the demo seem to append random hash to every slug, this isn't necessarily documented. With the laravel backend I've set the slug 'feed' to be reserved, something like this could be a solution.

- Restriction on tags with spaces since we don't make use of slugs for tags.

- Retrieving popular tag versus all tags. The best option would be to have another api which retrieves the top fixed number of tags to be used on the homepage .

## Postman
- Every user based test requires id, which is against the spec.

- No authorization token header on all the optional auth routes. This should be added by default so that it'll be easy testing these routes both when authenticated and not.

**Comment by EricSimons** [comment]
@SandeeshS thanks so much for this! We'll definitely accept your PR whenever you have time to submit it. Revamping our postman collection has been on the todo list, but the past week has been insane (in a good way:)

**Comment by SandeeshS** [comment]
This was fixed with https://github.com/gothinkster/realworld/pull/92
