### ISSUE TITLE
[RESOLVED] [Bug]: 500 No authorization token was found during PUT requests

### ISSUE THREAD

**Issue by concise-studio** [gothinkster/realworld#788]
### Relevant scope

Deployed demo

### Description

Currently if you try to do a PUT requests, API will answer you "No authorization token was found" with code 500.

At first, the authorization header in token is specified (see screenshot: https://ibb.co/x36vs2z)
At second, even if token not specified, I expect form API one of those errors:
- **400** Bad Request (if we consider missing Authorization as malformed request)
- **401** Unauthorized (if we do not care of token was not specified or not but sure that system cannot authorize user)
    
Can you, please, check the API and clarify what is wrong in my request and UI get this error.

Request params:
method: `PUT`
url: `https://conduit.productionready.io/api/user`
headers:   `Authorization: Token {token}`
body: `{"user":{"image":"https:\/\/realworld-temp-api.herokuapp.com\/images\/smiley-cyrus.jpeg","username":"Ya","bio":"ds","email":"kr1vetko@mail.ru"}}`

**Comment by geromegrignon** [comment]
Hey @concise-studio,

Thanks for pointing out this bug! I can reproduce it.
It's due to server redirection: the new API is hosted on `https://api.realworld.io` but there is a redirection to it from `https://conduit.productionready.io` to support existing implementations.

I don't have direct access to `https://conduit.productionready.io`, so I can't guarantee when I'll fix it.
I encourage you to use `https://api.realworld.io/api` (being used under the hood). I'll open an issue to update the documentation accordingly.

Please change the URL of the image to `https://conduit.productionready.io/images\smiley-cyrus.jpeg` as `https://realworld-temp-api.herokuapp.com` has been shut down a few days ago.
I'll open another issue to fix such a link in the new API as well.

**Comment by concise-studio** [comment]
Thank you, I switched the API Url and it works now
